apiVersion: v1
kind: Pod
metadata:
  name: my-llm-pod
  labels:
    app: llm
spec:
  containers:
  - name: llm-container
    image: 962804699607.dkr.ecr.us-west-2.amazonaws.com/hks-llm:latest
